### ISSUE TITLE
[Bug report] env: python3 no such file or directory

### ISSUE THREAD

**Issue by 1alessandro1** [section83/MacYTDL#50] opened 2022-01-05 14:36 UTC
Good evening, 

I've installed:

- MacYTDL 1.19.4 and 
- python3.9.9 [pkg](https://www.python.org/ftp/python/3.9.9/python-3.9.9-macosx10.9.pkg) and 
- The latest [yt-dlp](https://github.com/yt-dlp/yt-dlp/releases/download/2021.12.27/yt-dlp) to date in `/usr/local/bin` 
- alongside [ffmpeg](https://evermeet.cx/ffmpeg/ffmpeg-105153-g8abc192236.7z) and [ffprobe](https://evermeet.cx/ffmpeg/ffprobe-105153-g8abc192236.7z). 

I've also read in the documentation that to use MacYTDL with `yt-dlp` in macOS 10.14.6 (18G9323) I have to provide the following `.dylib`:

- `libcrypto.44.dylib`
- `libssl.46.dylib` 

Which were taken from a new macOS Catalina installation (build 19H1615 from 13-12-2021)

This is the current situation in `/usr/local`

![immagine](https://user-images.githubusercontent.com/46293832/148233020-95c1ad34-8acc-40cf-8fac-cee7006ab904.png)

However, when I make the switch to yt-dlp:

![immagine](https://user-images.githubusercontent.com/46293832/148233887-efcc423d-0bce-42b8-894b-349d17c95cc1.png)

even though I've pre-tested it from the command line:

![immagine](https://user-images.githubusercontent.com/46293832/148233255-6fe6fbf9-6bd9-4897-9b91-199e05a9c492.png)

I get the following error:

![immagine](https://user-images.githubusercontent.com/46293832/148233947-611d7b62-2c7a-468a-af1f-7b8b7859423b.png)

I think this problem is related to the fact that the python3.9.9 `.pkg` can't modify the `$PATH` for MacYTDL. I've tried to click on `Modify` and add it myself though:

Previously:
![immagine](https://user-images.githubusercontent.com/46293832/148234202-18f0ee59-d808-42f5-b346-1b86159b07a5.png)

After my modification:

![immagine](https://user-images.githubusercontent.com/46293832/148234325-df93aee1-4dc9-4406-8295-5ba09a420099.png)

But by doing so, the problem persists even after `sudo codesign --force --deep --sign - MacYTDL.app/` (since I edited the applescript)

Let me know what I can do to debug this issue on 10.14. 

FYI, MacYTDL works perfectly with just `youtube-dl` since it only uses the default python2.7 bundled in macOS.

**Comment by section83** [comment] 2022-01-05 21:43
Thank you for making contact.

The copy of YT-DLP installed by MacYTDL has Python 3.8 built in.  So, you do not need to install Python 3.9.  I am currently running MacYTDL on a Mojave install without the $PATH issue.  I will install Python 3.9 to test what happens.

AFAIK, code signing doesn't enable AppleScript to work.  Code signing will just make it harder to debug the issue.

I have [uploaded an unsigned copy of MacYTDL 1.19.4](https://github.com/section83/MacYTDL/releases/download/1.19.4/MacYTDL-v1.19.4-unsigned.zip).  You can edit the code in that without the code signing problem.

BTW, apologies for the lack of translation for much of MacYTDL. I hope to update the translations soon.

Interesting that the FFmpeg version number is so weird.  Is that a custom FFmpeg install or did MacYTDL handle the install ?

**Comment by section83** [comment] 2022-01-05 23:30
UPDATE:

I think the problem is that you installed the Unix executable of YT-DLP instead of the macOS executable.  I installed Python 3.9 and the Unix version of YT-DLP.  When I started MacYTDL I got the same error "env: python3: No such file or directory".

I do not know how to solve that problem. Did you follow the advice on [Docs.Python.org](https://docs.python.org/3.9/using/mac.html#configuration) ?

I have found a bug in the MacYTDL install code. So, I recommend you try this:

- delete this file: /Users/[your home]/Library/Preferences/MacYTDL/MacYTDL.plist;
- delete the Unix yt-dlp executable;
- run MacYTDL;
- agree to create the preferences file;
- hopefully, MacYTDL will display the Main dialog;
- click on Utilities;
- choose Switch to YT-DLP;
- hopefully, yt-dlp will be installed.

Let me know how you get on.

**Comment by 1alessandro1** [comment] 2022-01-05 23:39
Thanks for all of your support! It warms my heart that there are people who care about their users.

Tomorrow morning I'll reply to every question you've wrote above, and make the tests you asked for, thank you!

**Comment by section83** [comment] 2022-01-05 23:43
> Thanks for all of your support! It warms my heart that there are people who care about their users.

My pleasure. MacYTDL is my retirement project and I am very happy that people find it useful (when I fix the bugs).

Cheers.

**Closed** 2022-01-11 08:20 UTC

**Comment by 1alessandro1** [comment] 2022-01-11 09:37
Sorry for the delay, I was very busy last week and I couldn't find some time to reply...

Anyway, I followed your advice to remove the app and Preferences, update to v1.20 and let the app download YT-DLP and now everything works perfectly (with the additional libraries in /usr/local of course)

Many thanks for the support, and sorry for the delay again! 👍

**Comment by section83** [comment] 2022-01-11 09:40
> everything works perfectly

Now, I do like to see that !

Many thanks for the update.
