### ISSUE TITLE
Error running app in Ventura

### ISSUE THREAD

**Issue by Woolfy025** [section83/MacYTDL#59] opened 2022-11-02 05:00 UTC
Hello. I installed the app on my Macbook pro with ventura. Im not sure if this is a new error or, I forgot to install something prior. It's just the 1 error after the 'Note: Some components will be downloaded which might take a while and you will need to provide administrator credentials.' part.

![SCR-20221101-12f](https://user-images.githubusercontent.com/50890444/199402089-630d997e-e1d1-44cd-8cdb-63d3ec1fe380.jpeg)

**Comment by section83** [comment] 2022-11-02 08:56
Apologies for the problem. This should not happen and nothing you do should cause it.  At present I have no idea on the cause. So, I'm going to do some testing tomorrow (12-14 hours from now).

Many thanks for posting this issue.

**Comment by section83** [comment] 2022-11-02 23:36
I've done a clean install of MacYTDL in Ventura. Have also tested interrupting the download of components. It worked normally. So, I don't know why you got this error.

Do you remember doing anything after you got the 'Note: Some components will be downloaded which might take a while and you will need to provide administrator credentials.' dialog ? I guess you clicked on "Yes". Did anything happen after that ? Did you see any notifications e.g.:

<img width="346" alt="Screenshot 2022-11-03 at 10 24 21 am" src="https://user-images.githubusercontent.com/7471595/199620813-9bcff479-2c90-490b-a5bd-027aee0ad959.png">

The MacYTDL app can be stored anywhere but, it's always best to put it into the Applications folder.

Best option I can think of right now is for you to open MacYTDL again and let install anything it wishes. Provide admin credentials if asked. Note that downloading components (e.g. FFmpeg) can take some time during which MacYTD looks like it's doing nothing.

If you feel able, you could test MacYTDL. To do that, open the Script Editor app. It is located in the Applications/Utilities folder. You should see a choose file dialog. If not, choose the File menu then "Open...". Navigate to your copy of MacYTDL and open it. Press command-r.

If there is an error, the details will be in the "Log" pane in the bottom part of the Script Editor window. If you don't see the Log, choose the View menu and "Show Log".

Post here anything that happens. Screen captures are very useful.

Many thanks.

**Comment by Woolfy025** [comment] 2022-11-03 00:01
Thanks for the reply. I'll do what you mentioned and report back with what happened. appreciate it.

**Comment by Woolfy025** [comment] 2022-11-03 00:36
I had redownloaded it, and put it in the application folder and ran it. Looks to be like the same error as before. It still says that it will download some components. When I hit yes, I don't get anything asking for any admin credentials to enter. 

Only thing else that pops up is the screenshot I posted today.

I don't see anything in the 'Privacy and Security' tab.( The one that says: app store and identified developers'. Maybe it's not supposed to but, thought id let you know.)

I was able to get the logs off of Script Editor. For whatever reason it didn't like the fact I was trying to save it so, I transferred it to text files. Hope this helps!

[Events.txt](https://github.com/section83/MacYTDL/files/9924953/Events.txt)
[Messages-Results.txt](https://github.com/section83/MacYTDL/files/9924954/Messages-Results.txt)
[Replies.txt](https://github.com/section83/MacYTDL/files/9924955/Replies.txt)
<img width="376" alt="SCR-20221102-o8a" src="https://user-images.githubusercontent.com/50890444/199627362-ec75887d-fc99-42ac-bc18-19e5782dfaf6.png">

**Comment by section83** [comment] 2022-11-03 01:11
Many thanks for all that. It helps in narrowing down what is causing the problem.  The last event should return text of the web page but, for some reason it has returned nothing.

Regarding your 'Privacy and Security' setting, it should look like this:

<img width="487" alt="Security" src="https://user-images.githubusercontent.com/7471595/199630206-7e7e9b89-a5ae-4605-ba43-9fef3b242687.png">

You need to select "App Store and identified developers" because MacYTDL is downloaded from GitHub, not the App Store.

Can you try this please:

- Open "Terminal" (located in Applications/Utilities).
- Copy and paste this at the prompt: curl "https://github.com/yt-dlp/yt-dlp/releases" | textutil -stdin -stdout -format html -convert txt -encoding UTF-8

Let me know what you get. You should see something like this:

<img width="1028" alt="Screenshot 2022-11-03 at 12 05 03 pm" src="https://user-images.githubusercontent.com/7471595/199629928-ba97947e-2386-41cf-8154-e369319629cb.png">

**Comment by Woolfy025** [comment] 2022-11-03 01:20
<img width="1134" alt="SCR-20221102-pg9" src="https://user-images.githubusercontent.com/50890444/199631243-a9a779da-ce4c-49f4-b8d0-1632b14c1576.png">

**Comment by section83** [comment] 2022-11-03 05:06
Very odd.  I have seen errors like that in totally different situations which don't apply here.  I have forms of that AppleScript code which have been running without trouble for years.

I have put out a plea for help on my favourite AppleScript forum. Hopefully, one of the gurus will have an idea.

By any chance do you have your own special code or application which changes any environment variables ?  Don't worry if that doesn't mean anything.

You could manually download and install the various MacYTDL components. They are listed on page 55 of the "Help" file.

Sorry I can't suggest anything useful at present. I'll post here when I have more to offer.

**Comment by Woolfy025** [comment] 2022-11-03 09:01
The only thing I could think of is that Im just running a 2013 MBP with the 'opencore legacy patcher' software so I could install Ventura. I don't know if that could affect anything as everything seems to work without a problem. But, maybe it does have something to do with it not running properly if you already tried it yourself on ventura. 

The only other programs I have installed is VS code and / vscodium which is supposed to be similar in what it does. I was going to start trying to learn to code eventually, just getting things ready. All I have done so far is just have it install python I believe.

I'll delete those 2 apps and if that doesn't work, I'll do a fresh install. I hope that's all it was, and it starts running. Anyways, I'll check out the help file you mentioned and see if I can get it manually running. Appreciate your help with everything.

**Comment by Woolfy025** [comment] 2022-11-03 23:19
So, I reinstalled Ventura and tried to run it like before. It got to the point of me entering the Admin password(It didn't ask me last time), but the same error popped up as before. This was the first app I stuck in the Application folder and ran. Sounds like its not going to work on my machine for whatever reason.  Thanks for trying to figure it out though.

**Comment by section83** [comment] 2022-11-04 03:04
G'day. The OCLP could well be a factor. The error you got with that test in Terminal was not related to MacYTDL. You could contact the OCLP experts to ask about it. For example, I imagine that a Mac running OCLP might not show warning dialogs about permissions.

Ventura requires permissions to be given by the user for apps to do a range of things e.g. access the Desktop, access external volumes, control other apps etc. I have seen reports recently that there is a bug in the "Full Disk Access" permissions in Ventura.

So, another idea to try is to make sure that MacYTDL has all the permissions it needs.

- Open System Settings.
- Choose "Privacy & Security".
- Choose "Full Disk Access".
- Click on the "+" button.
- Provide admin credentials.
- Navigate to your copy of MacYTDL.
- Click on "Open".
- Check that the toggle is "On".

If MacYTDL already has Full Disk Access, delete it (using the "-" button) and add it back.

Back in "Privacy & Security":

- Choose "Automation".
- Hopefully MacYTDL is listed.
- Click on the little arrow located to the left of "MacYTDL".
- Check that "Finder" and "System Events" are listed.
- Toggle both off and on.

If MacYTDL is not listed in Automation permissions, hopefully, you will get a dialog asking about it if you can get MacYTDL to run.

Cheers.

**Comment by Woolfy025** [comment] 2022-11-04 05:53
Things I have noticed so far:

MacYTDL has ‘full disk access’ already set (I deleted it and added it again)

Second is that ‘Automation’ only had the ‘system events’ and ‘finder’ wasn’t an option. So far Ive tried it about 5 times with the same outcome. Damn this frustrating. Lol. I think I have the Catalina version which was the last Mac OS X version available for this Mac. so, I’m gonna try to install it on an external SSD and boot from it. If it ends up working, at least will know why. Ill let you know.

<img width="514" alt="SCR-20221103-vja" src="https://user-images.githubusercontent.com/50890444/199900128-ed617e42-fb08-4c5a-979f-b14479e8408a.png">

**Comment by Woolfy025** [comment] 2022-11-04 09:45
I just reinstalled Catalina back on and the install of MacYTDL works just fine. Didn't run to any errors or nothing. Maybe it's because it was the last version before we had to start using opencore for updates...maybe? 

What I'm gonna try to do (I think) is, install Big Sur or Monterey in hopes that it will work with the OS somewhat updated. If not, I'll probably just stick with Catalina for now. I'll send another message and let you know how it goes. I wonder if anyone else has similar issues like mine. Anyways, its nice to have it finally working!

**Comment by section83** [comment] 2022-11-04 23:13
I've not had any replies from my favourite experts on this. You can ask the OCLP community for help too. I suspect there are a number of issues with using Ventura in OCLP – it's a work in progress. Hopefully, things will be better with Monterey.

I'm going to develop a workaround. I really don't like the method I used to get text of a web page and there might be a way of doing that without causing your kind of error.

Cheers.

**Comment by section83** [comment] 2023-01-22 04:52
I've not been able to find out what might be causing this problem.  OCLP could be a part/whole cause.  There could also be permissions issues on the user account.

Anyway, closing this for now and can open a new issue if the problem recurs.

**Closed** 2023-01-22 04:52 UTC
