### ISSUE TITLE
sh: /usr/local/bin/yt-dlp: No such file or directory

### ISSUE THREAD

**Issue by EricTheDerek** [section83/MacYTDL#66] opened 2023-04-21 19:59 UTC
Hello. I'm trying to open the latest MacYTDL, but this error keeps popping up.
sh: /usr/local/bin/yt-dlp: No such file or directory

I've previously been using version 1.19.1, but that's been not working since youtube made some changes and I realized my updating has fallen behind.

I'm running on Catalina.

**Comment by section83** [comment] 2023-04-22 00:11
Hello [EricTheDerek](https://github.com/EricTheDerek), thank you for posting and letting me know about the problem.

It looks like a bug.  Can you help with some questions:

- Does MacYTDL open to the Main dialog ?  OR, does the error happen quickly when you try to start MacYTDL ?
- Are you using youtube-dl or yt-dlp ?
- Do you have an Homebrew install of yt-dlp ?
- Do you have a MacPorts install of yt-dlp ?
- Do you have "Check yt-dlp version on startup" turned on ?

If you are using youtube-dl you can change to yt-dlp. yt-dlp works with YouTube and has many more features. If you can't start MacYTDL you can switch manually:

- In the Finder Desktop, press command-shift-g.
- Type /usr/local/bin/  and Return.
- Delete the file called youtube-dl – you will need to enter administrator credentials.
- Try MacYTDL again – it might work and if so will ask if you want yt-dlp. Click on "OK"/"Yes"

If you are using a Homebrew install of yt-dlp, the only way to use v1.24 of MacYTDL is to remove the Homebrew install.  I goofed when adding Homebrew recognition, a problem which will be fixed in v1.25.

You could try version 1.23.1 of MacYTDL which, depending on the problem you are having, might work.

Thanks.

**Comment by GrantGochnauer** [comment] 2023-04-28 14:13
I am running into the same issue - just downloaded this for the first time today.

**Comment by section83** [comment] 2023-04-29 00:35
GrantGochnauer, thank you for posting. I have a fix for the Homebrew bug. I hope to upload a quick release in the next few days. I need to do more testing.

Is your Mac running on Apple Silicon or Intel ?

MacYTDL should work if you remove the Homebrew install of yt-dip.

**Comment by GrantGochnauer** [comment] 2023-04-29 00:37
Apple silicon. Thanks !

Grant Gochnauer / Founder; CTO / Vodori, Inc / 312.324.0124 Find Vodori on: Twitter / LinkedIn / Facebook

**Comment by section83** [comment] 2023-04-30 02:09
Should release v1.24.1 tomorrow. It should respect Homebrew installs of YT-DLP and FFmpeg.  If the startup works properly, the _Utilities_ dialog should look like this:

<img width="473" alt="Utilites - v1 24 1 - Homebrew installs of yt-dlp   ffmpeg" src="https://user-images.githubusercontent.com/7471595/235332085-f23e4e56-40e2-40d6-b628-cc258b1acfb3.png">

Any missing components will also be installed e.g. script library; preferences file.

**Comment by GrantGochnauer** [comment] 2023-04-30 11:29
Thanks! I will give it a try when it's ready.

**Comment by section83** [comment] 2023-05-01 05:30
Version 1.24.1 is out. I've tested the downloaded copy an on old Mac and found weird Finder errors which do not repeat. Hopefully, that's an artefact of my old Mac !

**Comment by GrantGochnauer** [comment] 2023-05-01 12:51
Thank you! Confirmed this version is working.

**Comment by section83** [comment] 2023-05-01 22:53
Many thanks for reporting back. Please post an issue/discussion or send an email if there are any features you would like added to MacYTDL.

**Closed by section83** 2023-05-01 22:53 UTC
Labels: Bug
